Traceback (most recent call last):
  File "/home/rjw/Documents/Projects/ESRF/jupyBookDemo/venv/lib64/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/rjw/Documents/Projects/ESRF/jupyBookDemo/venv/lib64/python3.6/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/rjw/Documents/Projects/ESRF/jupyBookDemo/venv/lib64/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/rjw/Documents/Projects/ESRF/jupyBookDemo/venv/lib64/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/rjw/Documents/Projects/ESRF/jupyBookDemo/venv/lib64/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/rjw/Documents/Projects/ESRF/jupyBookDemo/venv/lib64/python3.6/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/rjw/Documents/Projects/ESRF/jupyBookDemo/venv/lib64/python3.6/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%%bashls
------------------


UsageError: Cell magic `%%bashls` not found.

